# Generated by Django 5.1.3 on 2025-07-11 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc_cedula', models.CharField(max_length=100, unique=True)),
                ('celular', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('provincia', models.CharField(max_length=200)),
            ],
        ),
    ]
