# Generated by Django 5.1.3 on 2025-08-12 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_factura_detallefactura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('bundle_cantidad', models.PositiveIntegerField(help_text='Ej: 3 (por 3x)')),
                ('bundle_precio', models.DecimalField(decimal_places=2, help_text='Ej: 0.10', max_digits=10)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promocion', to='usuarios.producto')),
            ],
        ),
    ]
