# Generated by Django 5.1.3 on 2025-08-22 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_backfill_detalle_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='categoria_nombre',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='marca_nombre',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='producto_nombre',
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.producto'),
        ),
    ]
