# Generated by Django 5.1.3 on 2025-08-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_cleanup_detallefactura_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='pdf_archivo',
            field=models.FileField(blank=True, null=True, upload_to='facturas_pdf/'),
        ),
    ]
